# Generated by Django 2.1.7 on 2019-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190315_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(default='', help_text='微信用户绑定和CC视频统计', max_length=64, unique=True),
        ),
    ]
