# Generated by Django 2.1.7 on 2019-03-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190315_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionrecord',
            options={'verbose_name_plural': '40. 账号金额交易记录'},
        ),
        migrations.AddField(
            model_name='couponrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order', verbose_name='关联订单'),
        ),
    ]
